import { SafeAreaView } from 'react-native-safe-area-context';
import React, { useState } from 'react';
import { 
  View, 
  Text, 
  ScrollView, 
  StyleSheet, 
  TouchableOpacity, 
  StatusBar 
} from 'react-native';
import { Shield, FileText, Lock, ArrowLeft, AlertTriangle, CheckCircle, Info, HeartPulse } from 'lucide-react-native';

const TermsPrivacyScreen = ({ navigation, route }) => {
  const initialTab = route?.params?.tab || 'terms';
  const [activeTab, setActiveTab] = useState(initialTab);

  return (
    <SafeAreaView style={styles.container}>
      <StatusBar barStyle="light-content" backgroundColor="#0f172a" />
      
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity style={styles.backBtn} onPress={() => navigation.goBack()}>
          <ArrowLeft size={20} color="#fff" />
        </TouchableOpacity>
        <View style={styles.headerTitleContainer}>
          <Text style={styles.headerTitle}>Legal & Privacy</Text>
          <Text style={styles.headerSubtitle}>Terms of Service & Privacy Policy</Text>
        </View>
        <View style={{ width: 36 }} />
      </View>

      {/* Segmented Tab Bar */}
      <View style={styles.tabContainer}>
        <TouchableOpacity 
          style={[styles.tabBtn, activeTab === 'terms' && styles.tabBtnActive]}
          onPress={() => setActiveTab('terms')}
        >
          <FileText size={16} color={activeTab === 'terms' ? '#fff' : '#94a3b8'} />
          <Text style={[styles.tabText, activeTab === 'terms' && styles.tabTextActive]}>Terms of Service</Text>
        </TouchableOpacity>

        <TouchableOpacity 
          style={[styles.tabBtn, activeTab === 'privacy' && styles.tabBtnActive]}
          onPress={() => setActiveTab('privacy')}
        >
          <Lock size={16} color={activeTab === 'privacy' ? '#fff' : '#94a3b8'} />
          <Text style={[styles.tabText, activeTab === 'privacy' && styles.tabTextActive]}>Privacy Policy</Text>
        </TouchableOpacity>
      </View>

      <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
        {activeTab === 'terms' ? (
          <View style={styles.sectionContainer}>
            {/* Disclaimer Banner */}
            <View style={styles.disclaimerBanner}>
              <View style={styles.disclaimerHeader}>
                <AlertTriangle size={18} color="#f59e0b" />
                <Text style={styles.disclaimerTitle}>MEDICAL DISCLAIMER</Text>
              </View>
              <Text style={styles.disclaimerText}>
                Aura AI does NOT provide licensed medical advice or diagnostic medical care. Predictions and report breakdowns are generated by AI models for informational self-assessment only. Always consult a licensed doctor regarding health conditions. In a medical emergency, call emergency services immediately.
              </Text>
            </View>

            {/* Card 1 */}
            <View style={styles.card}>
              <View style={styles.cardHeader}>
                <CheckCircle size={18} color="#3b82f6" />
                <Text style={styles.cardTitle}>1. Acceptance of Terms</Text>
              </View>
              <Text style={styles.cardBody}>
                By creating an account or using Aura AI, you agree to these Terms. If you do not agree, please discontinue using the service.
              </Text>
            </View>

            {/* Card 2 */}
            <View style={styles.card}>
              <View style={styles.cardHeader}>
                <HeartPulse size={18} color="#3b82f6" />
                <Text style={styles.cardTitle}>2. AI Features & Emergency SOS</Text>
              </View>
              <Text style={styles.cardBody}>
                Symptom classifications and lab report metrics use machine learning models. Predictions are statistical estimates. Emergency SOS alerts rely on cellular networks and internet connectivity.
              </Text>
            </View>

            {/* Card 3 */}
            <View style={styles.card}>
              <View style={styles.cardHeader}>
                <Info size={18} color="#3b82f6" />
                <Text style={styles.cardTitle}>3. User Responsibilities</Text>
              </View>
              <Text style={styles.cardBody}>
                You agree to keep credentials secure and provide accurate health details. Accounts misusing AI systems or submitting false emergency alerts will be suspended.
              </Text>
            </View>
          </View>
        ) : (
          <View style={styles.sectionContainer}>
            {/* Privacy Promise Banner */}
            <View style={styles.privacyBanner}>
              <View style={styles.disclaimerHeader}>
                <Lock size={18} color="#10b981" />
                <Text style={styles.privacyTitle}>OUR PRIVACY COMMITMENT</Text>
              </View>
              <Text style={styles.privacyText}>
                Your health data belongs strictly to you. Aura AI NEVER sells, rents, or shares your medical lab reports or symptom logs with advertisers or third parties.
              </Text>
            </View>

            {/* Card 1 */}
            <View style={styles.card}>
              <View style={styles.cardHeader}>
                <Shield size={18} color="#3b82f6" />
                <Text style={styles.cardTitle}>1. Information Collected</Text>
              </View>
              <Text style={styles.cardBody}>
                We collect your profile information, reported symptoms, uploaded lab report PDFs, and GPS location coordinates strictly when you trigger the Emergency SOS button.
              </Text>
            </View>

            {/* Card 2 */}
            <View style={styles.card}>
              <View style={styles.cardHeader}>
                <Lock size={18} color="#3b82f6" />
                <Text style={styles.cardTitle}>2. Security & Encryption</Text>
              </View>
              <Text style={styles.cardBody}>
                All communication between mobile app and servers is encrypted via TLS 1.3/HTTPS. User health data and parsed PDF vector stores are isolated per session.
              </Text>
            </View>

            {/* Card 3 */}
            <View style={styles.card}>
              <View style={styles.cardHeader}>
                <CheckCircle size={18} color="#3b82f6" />
                <Text style={styles.cardTitle}>3. Data Erasure Rights</Text>
              </View>
              <Text style={styles.cardBody}>
                You can delete active document contexts, clear your chat histories, or request total account erasure at any time in Profile Settings.
              </Text>
            </View>
          </View>
        )}
      </ScrollView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0f172a',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#1e293b',
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#1e293b',
    justify: 'center',
    alignItems: 'center',
  },
  headerTitleContainer: {
    alignItems: 'center',
  },
  headerTitle: {
    color: '#fff',
    fontSize: 17,
    fontWeight: 'bold',
  },
  headerSubtitle: {
    color: '#94a3b8',
    fontSize: 11,
    marginTop: 2,
  },
  tabContainer: {
    flexDirection: 'row',
    marginHorizontal: 20,
    marginTop: 16,
    backgroundColor: '#1e293b',
    borderRadius: 14,
    padding: 4,
  },
  tabBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    borderRadius: 10,
    gap: 8,
  },
  tabBtnActive: {
    backgroundColor: '#1d4ed8',
  },
  tabText: {
    color: '#94a3b8',
    fontSize: 13,
    fontWeight: '600',
  },
  tabTextActive: {
    color: '#fff',
    fontWeight: 'bold',
  },
  scrollContent: {
    padding: 20,
  },
  sectionContainer: {
    gap: 16,
  },
  disclaimerBanner: {
    backgroundColor: 'rgba(245, 158, 11, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.3)',
    borderRadius: 16,
    padding: 16,
  },
  disclaimerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  disclaimerTitle: {
    color: '#f59e0b',
    fontSize: 12,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  disclaimerText: {
    color: '#fef3c7',
    fontSize: 12,
    lineHeight: 18,
  },
  privacyBanner: {
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.3)',
    borderRadius: 16,
    padding: 16,
  },
  privacyTitle: {
    color: '#10b981',
    fontSize: 12,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  privacyText: {
    color: '#d1fae5',
    fontSize: 12,
    lineHeight: 18,
  },
  card: {
    backgroundColor: '#1e293b',
    borderRadius: 16,
    padding: 18,
    borderWidth: 1,
    borderColor: '#334155',
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
  },
  cardTitle: {
    color: '#fff',
    fontSize: 15,
    fontWeight: 'bold',
  },
  cardBody: {
    color: '#cbd5e1',
    fontSize: 13,
    lineHeight: 20,
  },
});

export default TermsPrivacyScreen;
